apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: lb
  name: lb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: lb
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/network: "true"
        io.kompose.service: lb
    spec:
      containers:
        - env:
            - name: BACKENDS
              value: hidden-dragon
            - name: BACKENDS_PORT
              value: "8080"
            - name: COOKIES_ENABLED
              value: "false"
            - name: DNS_ENABLED
              value: "true"
            - name: LOG_LEVEL
              value: info
          image: eeacms/haproxy
          name: lb
          ports:
            - containerPort: 5000
            - containerPort: 1936
          resources: {}
      restartPolicy: Always
status: {}
