create table cart (cart_id integer not null, user_id integer, primary key (cart_id)) engine=InnoDB;
create table cart_item (item_id integer not null, quantity integer, cart_cart_id integer, item_item_id integer, primary key (item_id)) engine=InnoDB;
create table drug_store_command (id bigint not null, action varchar(255), address varchar(255), cardcvv varchar(255), cardexpyear varchar(255), cardnum varchar(255), city varchar(255), email varchar(255), firstname varchar(255), lastname varchar(255), notes varchar(255), password varchar(255), phone varchar(255), state varchar(255), user_id integer, username varchar(255), zip varchar(255), primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table item (item_id integer not null, item_name varchar(255), price integer, stock integer, primary key (item_id)) engine=InnoDB;
create table user (user_id integer not null, password varchar(255), username varchar(255), primary key (user_id)) engine=InnoDB;
alter table cart_item add constraint FK7vsju2wftw7285wp7maxhi2pd foreign key (cart_cart_id) references cart (cart_id);
alter table cart_item add constraint FKg488ogpd18rrfwvqwoef6ui23 foreign key (item_item_id) references item (item_id);
create table cart (cart_id integer not null, user_id integer, primary key (cart_id)) engine=InnoDB;
create table cart_item (item_id integer not null, quantity integer, cart_cart_id integer, item_item_id integer, primary key (item_id)) engine=InnoDB;
create table drug_store_command (id bigint not null, action varchar(255), address varchar(255), cardcvv varchar(255), cardexpyear varchar(255), cardnum varchar(255), city varchar(255), email varchar(255), firstname varchar(255), lastname varchar(255), notes varchar(255), password varchar(255), phone varchar(255), state varchar(255), user_id integer, username varchar(255), zip varchar(255), primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table item (item_id integer not null, item_name varchar(255), price integer, stock integer, primary key (item_id)) engine=InnoDB;
create table user (id integer not null, password varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
alter table cart_item add constraint FK7vsju2wftw7285wp7maxhi2pd foreign key (cart_cart_id) references cart (cart_id);
alter table cart_item add constraint FKg488ogpd18rrfwvqwoef6ui23 foreign key (item_item_id) references item (item_id);
create table cart (cart_id integer not null, user_id integer, primary key (cart_id)) engine=InnoDB;
create table cart_item (item_id integer not null, quantity integer, cart_cart_id integer, item_item_id integer, primary key (item_id)) engine=InnoDB;
create table drug_store_command (id bigint not null, action varchar(255), address varchar(255), cardcvv varchar(255), cardexpyear varchar(255), cardnum varchar(255), city varchar(255), email varchar(255), firstname varchar(255), lastname varchar(255), notes varchar(255), password varchar(255), phone varchar(255), state varchar(255), user_id integer, username varchar(255), zip varchar(255), primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table item (item_id integer not null, item_name varchar(255), price integer, stock integer, primary key (item_id)) engine=InnoDB;
create table user (user_id integer not null, password varchar(255), username varchar(255), primary key (user_id)) engine=InnoDB;
alter table cart_item add constraint FK7vsju2wftw7285wp7maxhi2pd foreign key (cart_cart_id) references cart (cart_id);
alter table cart_item add constraint FKg488ogpd18rrfwvqwoef6ui23 foreign key (item_item_id) references item (item_id);
