version: "3"

services:
  rabbitmq:
    image: rabbitmq:management
    volumes:
      - /mySql:/mySql
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - network
  mysql:
    image: mysql:8.0
    volumes:
      - /mySql:/mySql
    networks:
      - network   
    ports:
      - 3306    
    networks:
      - network
    environment:
      MYSQL_ROOT_PASSWORD: "cmpe172"
    restart: always  
         
  drugStore:
    image: hidden-dragon
    depends_on:
    - mysql    
    volumes:
      - /mySql:/mySql
    networks:
      - network   
    ports:
      - 8080    
    environment:
      MYSQL_HOST: "mysql"
      RABBIT_HOST: "rabbitmq"
    restart: always     
  lb:
    image: eeacms/haproxy
    depends_on:
    - drugStore
    ports:
    - "80:5000"
    - "1936:1936"
    environment:
      BACKENDS: "hidden-dragon"
      BACKENDS_PORT: "8080"
      DNS_ENABLED: "true"
      COOKIES_ENABLED: "false"
      LOG_LEVEL: "info"
    networks:
      - network

volumes:
  schemas:
    external: false

networks:
  network:
    driver: bridge